# Generated by Django 3.0.6 on 2020-08-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(null=True, verbose_name='상품가격'),
        ),
    ]
