# Generated by Django 3.0.6 on 2020-08-11 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_post_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
