# Generated by Django 3.0.6 on 2020-08-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_remove_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
