# Generated by Django 3.0.6 on 2020-08-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20200811_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='grade',
            field=models.IntegerField(null=True, verbose_name='평점'),
        ),
    ]
