# Generated by Django 3.0.6 on 2020-08-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_review_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
