# Generated by Django 3.0.6 on 2020-08-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20200811_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='상품재고'),
        ),
    ]
