# Generated by Django 3.0.6 on 2020-08-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_remove_comment_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='writer',
        ),
        migrations.AddField(
            model_name='comment',
            name='grade',
            field=models.IntegerField(null=True, verbose_name='평점'),
        ),
    ]
